version: '3'
services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth
    image: simple-auth:v1
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: users
      MONGODB_USERNAME: auth_service
      MONGODB_PASSWORD: WtfWtfWtf
      MONGODB_HOSTNAME: mongodb
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: auth_service
      MONGO_INITDB_ROOT_PASSWORD: WtfWtfWtf
      MONGO_INITDB_DATABASE: users
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db

volumes:
    mongodbdata:
        driver: local